networks:
  dockerapi-dev:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - dockerapi-dev
    environment:
      - "ConnectionStrings:dbConnection=User ID =admin;Password=admin;Server=db;Port=5432;Database=dev-db;Integrated Security=true;Pooling=true;"

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: "dev-db"
    networks:
      - dockerapi-dev
